% ExampleODE_run.m
 % Automatically generated by Netflux on 09-May-2025

 % Load parameters
 [params,y0] = ExampleODE_loadParams();

 % Run single simulation
 tspan = [0 10];
 options = [];
 [t,y] = ode15s(@ExampleODE,tspan,y0,options,params);

 % Plot results
 figure;
 plot(t,y);
 xlabel('Time (sec)');
 ylabel('Fractional Species Activation');
 speciesNames = params{4};
 legend(speciesNames); 
